[meta]
name            = "Tweaker Preview"
author          = "fentras LABS"
category        = "Settings"
version         = "220729"
siteid          = 221
blocks          = ["Tweaker"]

[script]
timeout         = 10000
dependencies    = ["VehicleState"]